language: node_js

os:
  - linux
  - osx

node_js:
  - "6"
  - "8"
  - "node" # latest stable Node.js release

before_script:
  - npm install mocha eslint -g

notifications:
  email:
    on_success: never
    on_failure: always
